# Generated by Django 2.0.1 on 2018-03-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('email', 'password')},
        ),
    ]
