# Generated by Django 2.0.1 on 2018-03-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webApp', '0002_auto_20180327_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
